name: Build Project

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: keshavagarwal159/github-actions-template/.github/workflows/maven-build-template.yml@master
    secrets: inherit